#!/bin/sh
set -e

### BEGIN INIT INFO
# Provides:		phidgetwebservice
# Required-Start:	$local_fs $syslog $network
# Required-Stop:	$local_fs $syslog $network
# X-Start-Before:	rocket-commander-LTC
# Should-Start:		$syslog
# Should-Stop:		$syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Phidget web service
### END INIT INFO

DAEMON=/usr/bin/phidgetwebservice21
DAEMON_ARGS=""
PIDFILE=/var/run/phidgetwebservice.pid

case "$1" in
    start)
	start-stop-daemon --start --quiet --pidfile $PIDFILE -b -m --exec $DAEMON -- $DAEMON_ARGS
        ;;
    stop)
	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --exec $DAEMON
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac

exit 0
