= Portland State Aerospace Society Launch Tower Computer 3 Design Specification
PSAS Avionics Team <psas-avionics@lists.psas.pdx.edu>
v0.1, 24 October 2015: DRAFT

:imagesdir: ./images


NB: This document is most totally a work in progress.  In fact, you
probably shouldn't even bother to read the following words unless
you're planning on editing them.  Move along, people...



== Summary

This document is the source of authority for all questions related to
the design and implementation of the third PSAS Launch Tower Computer
(LTC3).  If the design of LTC3 doesn't conform to this document, then
either the design is incorrect, or the document needs to be updated!



== Power

=== Sources
Power for LTC3 will be sourced from a bench power supply while in the
lab, and photovoltaic panels while in the field.

Minimum input voltage is determined by the DC-DC converter supplying
the 19 VDC rail, which requires an overhead of 4 VDC.  At minimum, a
24 VDC supply capable of sourcing at least TODO 10 amps is required.
footnote:[Refer to Texas Instruments PTN78020[WH\] datasheet, Aug.
2011, page 10, "Input Voltage Considerations"]

=== Battery
The heart of the LTC3 power circuitry is a 28.8 V, 8s2p LiPo battery
pack.  The 28.8 V nominal voltage enables the use of buck converters
on 5V and 19V power rails.  (Configurable buck converters are cheap
and plentiful, and have higher efficiencies than the boost
converters.)  The 8s2p configuration enables us to charge-balance
individual cells.

The downside of this approach is the need for a custom charging
circuit, as most off-the-shelf chargers are designed for 12V nominal
MPPT and 4s cell configurations.

==== TODO
* Based on assumptions: 90% efficiency, calc. 96W of power (a
  conservative estimate), 4 hours pure battery, we need a capacity of
  13.2Ah at 28.8V nominal.
* An 8s2p final configuration of 6.7 Ah cells would get
  us into our 4 hours.

==== Charge Controller
LTC3 uses the Linear Technologies LT8490, a switching buck/boost
regulator that integrates a charger and solar MPPT.  It is robust and
inexpensive.  Implementation of circuits based on the LT8490 are
somewhat complicated, but are a big win in terms of cost and system
flexibility.  The LT8490 can be powered with a wide range of input
voltages.  A single connctor can be used for either the solar panels
or 12V bench power supplies.

==== Battery Management and Cell Protection
LiPo cell protection is provided by a Texas Instruments bq77PL900
("bq").  The bq performs both battery balancing and protection
for up to 10 lithium-polymer cells.  Cell balancing and protection
prevent over-charging and -discharging of cells, giving the batteries
extra run time and lifespan.  It also prevents the overheating of
cells (a fire hazard), and prevents early capacity degradation.

===== Basic Function
The bq utilizes two different PMOS devices, which are turned on and
off by a microcontroller in the chip.  The bq senses battery cell
voltages through its VC pins (VC1-VC10).  When the battery's voltage
grows too high, the bq applies a voltage to the gates of the PMOS CHG
FETs, whose body diodes then prevent current from passing from the
input to the battery.  Likewise, when the battery's voltage drops too
low, the bq applies a voltage on the gates of the DSG PMOS FETs, whose
body diodes prevent current from passing from the battery to the load.
The charge pump built into the bq allows gate voltages to become high
enough for the CHG and DSG FETs to switch on and off.

===== Active Balancing
The bq uses active balancing in its design.  To do this, an integrated
NMOS in the chip is connected between two of the VC pins and turns on
when a certain voltage drops across it.  As a result, if one cell's
voltage is too much greater than another, the voltage drop across the
NMOS pushes current to the adjacent cell, and so on and so forth.  An
external 500Ω current-limiting resistor is used in conjunction with a
0.1μF filter capacitor.

===== Temperature Sensing
The temperature sensing feature of our design revolves around the TOUT
and TIN pins on the bq.  A voltage divider network is put in parallel
with a 10kΩ thermistor, which is taped to the battery pack.  The
thermistor's resistance decreases with increasing temperature (NTC).
When the battery pack gets hot, the voltage on the TIN pin becomes
low, turning off both the DSG and CHG FETs.  This prevents current
from flowing into our out of the battery, allowing it time to cool
off.  Once the temperature has stabilized, the bq resumes its regular
function.

===== Zero-Volt Charging
The zero-volt charging in our design is driven by another PMOS device
via the general-purposed open-drain ("GPOD") pin.  When voltage drops
below the supply voltage of the bq, the 0-V/precharge is enabled.
When this happens, the GPOD pin drives the 0-V/precharge FET (Q306 in
the LTC3 schematic).  When this FET is turned on, the CHG FET is
bypassed and current passes through the GPOD FET, allowing the battery
to charge.  When the voltage reaches a sustainable level for the bq to
operate, the GPOD FET is turned off and the CHG FET takes over.

===== Shutdown Mode
When undervoltage is detected, the bq goes into shutdown mode.  In
this mode, the DSG FET is turned off and all functions of the bq
cease.  To exit shutdown mode, a voltage greater than V~STARTUP~ must
be applied on the PACK+ pin.  This can be done in our system by
applying an output voltage from the LT8490 onto the PACK+ pin of the
bq.


=== DC Rails
LTC3 provides three DC power rails:

* 5 VDC for the Beaglebone and cape
* 12 VDC for the Ethernet switch and external device support
* 19 VDC for rocket shore power

DC power rails are supplied by separate Texas Instruments PTN78020
switching regulator ICs.  The PTN78020 is a wide-input, wide-output,
adjustable 6 A regulator.  A PTN78020W converter is used for the 5 VDC
rail; PTN78020H converters are used for the 12 VDC and 19 VDC rails.

Based on the temperature derating curves in the PTN78020 datasheet
(rev. Aug. 2011), our worst case scenario is 4.0A load on the 12V DC
rail.  Fig. 21 in the datasheet indicates that the maximum ambient
temperature for such a load is approximately 55 °C.

.LTC3 DC Power Rails
[width="25%",frame="topbot",options="header"]
|=======================================
| V~out~ | I~min~ | I~typ~ | I~max~ | technology 
| 5.0  | ?    | 1.0  | 2.0  | PTN78020W
| 12.0 | ?    | ?    | 5.0  | PTN78020H
| 19.0 | ?    | 3.0  | 4.0  | PTN78020H
|=======================================



== Ignition Subsystem

The ignition system functions off three different relays.  The rocket,
which is connected with an umbilical cord, tells the LTC it is
prepared to launch by sending a "ROCKET_READY" signal to the LTC.
This activates a solid state relay (IC601) which pushes signal to the
following AND gate.

When the LTC sees the rocket ready signal and shore power, after a 5
second delay the second relay (K601) is triggered. Additionally, an
LED lights up indicating the rocket is "ready to launch," and assuming
the relay locks, the first light on the "BAKERCON" indicator will
light up.

The third relay is activated by the "ROCKET_IGNITE" pin from the
beaglebone on the LTC3. At this point the second light on the BAKERCON
idicator is lit.  When this signal is active, the third relay (K602)
closes and the system goes through a breaker arm, switch, and banana
jack to ensure launch is desired. When these three are connected, the
third and final BAKERCON indicator light is active.

The final step to launching the rocket is connecting the short-bar,
known as the launch key, to the away box.  When all of these
conditions have been met, the rocket will launch.



== Computer

The heart of LTC3 is a BeagleBone Black (BBB) single-board computer.

The BBB interfaces with the main board via a pair of 46-pin headers.
The main board appears to the BBB as a standard
http://beagleboard.org/cape["cape"].  The main board is on the bottom,
with the BBB mounted on top, upside-down.

=== Cape EEPROM Contents
TODO



== Sensors

LTC3 contains sensors to monitor the voltage and current sourced from
the photovoltaic panels; sourced from the main battery; and sunk on
the 5 VDC, 12 VDC, and 19 VDC rails.

Sensing of voltage, current and temperature alike is accomplished with
a pair of http://cds.linear.com/docs/en/datasheet/2991fd.pdf[Linear
Technologies LTC2991] _Octal I2C Voltage, Current, and Temperature
Monitor_ ICs.  One IC is dedicated to the LTC3's power sources, the
other to its sinks.  The ICs interface with the BeagleBone via an I2C
bus.

The temperature sensor integral to each LTC2991 will be used to
monitor the LTC3 main board.  An MMBT3904 NPN BJT connected to the
first LTC2991 (same IC used to monitor the power sources' voltage and
current) will be used to monitor the temperature of the main battery.



== Networking

* Internal Ethernet switch.



== External Device Support

LTC3 provides power and trigger support for four external devices
(e.g., cameras).

=== Power
Power is supplied through two-terminal Anderson Powerpole connectors,
available from the exterior of the LTC enclosure.  Current to each
connector is limited by a 2 A PPTC (PolyFuse).

Each power connector is controlled independently by the computer.
Photorelays, driven via GPIO through a MOSFET, are used to switch the
12 VDC rail to "Eurostyle" connectors mounted to the mainboard.
Common, 16-gauge stranded copper wire carries current from the
on-board connectors to the exterior-facing Powerpoles.

=== Triggers
Triggering is supplied through two-terminal TODO-CONNECTOR_TYPE
connectors, available from the exterior of the LTC enclosure.  Current
to each connector is limited by a 500mA A PPTC (PolyFuse).

Each trigger connector is controlled independently by the computer.
Photorelays, driven via GPIO through a MOSFET, are used to switch
either ground, or the 5 VDC rail, to "Eurostyle" connectors mounted to
the mainboard.  An on-board three-pin header is jumpered accordingly
to select the signal, whichever suits the device being triggered.



== User Interface

=== BAKERCON Hazard Gauge
Indicates at a glance how close ignition battery power is to the
rocket ignition outlet (to which the away box is connected).  Three
super-bright LED indicators are mounted to the enclosure exterior.
The first, yellow, lights when the ignition battery relay closes.  The
second, also yellow, lights when the rocket ignition relay closes.
The third, red, lights when power reaches the outlet.

The ignition sub-system is still fully functional when the 12V and 19V
supplies are disabled.  Thus, the BAKERCON is powered off of the 5V
supply.



== Physical

=== Printed Circuit Board
Trace widths must be sufficient minimize circuit impedance, and to
limit temperature rise.  Assume a maximum ambient temperature
(enclosure interior) of 60°C.  Maximum trace temperature rise should
be no more than 20°C.

=== External Connectors
IDEA: Powerpole connectors are mounted to the enclosure with
http://www.portableuniversalpower.com/anderson-autogrip/[Anderson
AutoGrips].  They're robust and inexpensive.
