= Portland State Aerospace Society Launch Tower Computer III Design Specification
PSAS Avionics Team <psas-avionics@lists.psas.pdx.edu>
v0.1, 24 February 2015: DRAFT

:imagesdir: ./images


NB: This document is most totally a work in progress.  In fact, you
shouldn't even read the following words unless you're planning on
editing them.  Move along, people...



== Summary

This document is the source of authority for all questions related to
the design and implementation of the LTC III.  If the design of the
LTC doesn't conform to this document, then either the design is
incorrect, or the document needs to be updated!



== Computer

TODO: More words, please.

* BeagleBone Black SBC

* BBB flipped upside down and mated to peripheral board via pin
  headers.  A kilt, rather than a cape!



== Power Sources

* 12V nominal input from an external wall-mount power supply

* 17V (open circuit) PV power input

** MPPT?

* Internal LiPo power pack (10,14.4,16.8)V @ ??? AHr

** Battery charger from PV? Shore power?



== Power Supplies



== Ignition Subsystem
* The ignition signal is controlled by two relays in series
** One on the ignition board controlled by RocketReady (from the FC)
** One on the relay board controlled by the LTC



== Networking

* Internal Ethernet switch.



== References

http://kilobaser.com/blog/2014-07-15-beaglebone-black-gpios["BeagleBone
Black GPIOs"], KiloBaser.
