= Portland State Aerospace Society Launch Tower Computer 3 Design Specification
PSAS Avionics Team <psas-avionics@lists.psas.pdx.edu>
v0.1, 24 October 2015: DRAFT

:imagesdir: ./images


NB: This document is most totally a work in progress.  In fact, you
probably shouldn't even bother to read the following words unless
you're planning on editing them.  Move along, people...



== Summary

This document is the source of authority for all questions related to
the design and implementation of the third PSAS Launch Tower Computer
(LTC3).  If the design of LTC3 doesn't conform to this document, then
either the design is incorrect, or the document needs to be updated!



== Power

=== Sources

Power for LTC3 will be sourced from a bench power supply while in the
lab, and photovoltaic panels while in the field.

Minimum input voltage is determined by the DC-DC converter supplying
the 19 VDC rail, which requires an overhead of 4 VDC.  At minimum, a
24 VDC supply capable of sourcing at least TODO 10 amps is required.
footnote:[Refer to Texas Instruments PTN78020[WH\] datasheet, Aug.
2011, page 10, "Input Voltage Considerations"]


=== Battery

The heart of the LTC3 power circuitry is a 28.8 V, 8s2p LiPo battery
pack.  The 28.8 V nominal voltage enables the use of buck converters
on 5V and 19V power rails.  (Configurable buck converters are cheap
and plentiful, and have higher efficiencies than the boost
converters.)  The 8s2p configuration enables us to charge-balance
individual cells.

The downside of this approach is the need for a custom charging
circuit, as most off-the-shelf chargers are designed for 12V nominal
MPPT and 4s cell configurations.

==== TODO

* Based on assumptions: 90% efficiency, calc. 96W of power (a
  conservative estimate), 4 hours pure battery, we need a capacity of
  13.2Ah at 28.8V nominal.
* An 8s2p final configuration of 6.7 Ah cells would get
  us into our 4 hours.

==== Charge Controller

LTC3 uses the Linear Technologies LT8490, a switching buck/boost
regulator that integrates a charger and solar MPPT.  It is robust and
inexpensive.  Implementation of circuits based on the LT8490 are
somewhat complicated, but are a big win in terms of cost and system
flexibility.  The LT8490 can be powered with a wide range of input
voltages.  A single connctor can be used for either the solar panels
or 12V bench power supplies.

==== Protection

LiPo cell protection is provided by a Texas Instruments bq77PL900.
The bq77PL900 is a cell protector and charge balancer that is
inexpensive and relatively simple to use.


=== DC Rails

LTC3 provides three DC power rails:

* 5 VDC for the Beaglebone and cape
* 12 VDC for the Ethernet switch and external device support
* 19 VDC for rocket shore power

DC power rails are supplied by separate Texas Instruments PTN78020
switching regulator ICs.  The PTN78020 is a wide-input, wide-output,
adjustable 6 A regulator.  A PTN78020W converter is used for the 5 VDC
rail; PTN78020H converters are used for the 12 VDC and 19 VDC rails.

Based on the temperature derating curves in the PTN78020 datasheet
(rev. Aug. 2011), our worst case scenario is 4.0A load on the 12V DC
rail.  Fig. 21 in the datasheet indicates that the maximum ambient
temperature for such a load is approximately 55 °C.

.LTC3 DC Power Rails
[width="25%",frame="topbot",options="header"]
|=======================================
| Vout | Imin | Ityp | Imax | technology 
| 5.0  | ?    | 1.0  | 2.0  | PTN78020W
| 12.0 | ?    | ?    | 5.0  | PTN78020H
| 19.0 | ?    | 3.0  | 4.0  | PTN78020H
|=======================================


== Ignition Subsystem
* The ignition signal is controlled by two relays in series
** One on the ignition board controlled by RocketReady (from the FC)
** One on the relay board controlled by the LTC



== Computer

The heart of LTC3 is a BeagleBone Black (BBB) single-board computer.

The BBB interfaces with the main board via a pair of 46-pin headers.
The main board appears to the BBB as a standard
http://beagleboard.org/cape["cape"].  The main board is on the bottom,
with the BBB mounted on top, upside-down.

=== Cape EEPROM Contents
TODO



== Sensors

LTC3 contains sensors to monitor the voltage and current sourced from
the photovoltaic panels; sourced from the main battery; and sunk on
the 5 VDC, 12 VDC, and 19 VDC rails.

Sensing of voltage, current and temperature alike is accomplished with
a pair of http://cds.linear.com/docs/en/datasheet/2991fd.pdf[Linear
Technologies LTC2991] _Octal I2C Voltage, Current, and Temperature
Monitor_ ICs.  One IC is dedicated to the LTC3's power sources, the
other to its sinks.  The ICs interface with the BeagleBone via an I2C
bus.

The temperature sensor integral to each LTC2991 will be used to
monitor the LTC3 main board.  An MMBT3904 NPN BJT connected to the
first LTC2991 (same IC used to monitor the power sources' voltage and
current) will be used to monitor the temperature of the main battery.



== Networking

* Internal Ethernet switch.


== External Device Support

LTC3 provides power and trigger support for four external devices
(e.g., cameras).

=== Power
Power is supplied through two-terminal Anderson Powerpole connectors,
available from the exterior of the LTC enclosure.  Current to each
connector is limited by a 2 A PPTC (PolyFuse).

TODO: 2 A x 4 external devices exceeds the TI DC-DC converter's max
rating.

Each power connector is controlled independently by the computer.
Photorelays, driven via GPIO through a MOSFET, are used to switch the
12 VDC rail to "Eurostyle" connectors mounted to the mainboard.
Common, 16-gauge stranded copper wire carries current from the
on-board connectors to the exterior-facing Powerpoles.

=== Triggers
Triggering is supplied through two-terminal TODO-CONNECTOR_TYPE
connectors, available from the exterior of the LTC enclosure.  Current
to each connector is limited by a 500mA A PPTC (PolyFuse).

Each trigger connector is controlled independently by the computer.
Photorelays, driven via GPIO through a MOSFET, are used to switch
either ground, or the 5 VDC rail, to "Eurostyle" connectors mounted to
the mainboard.  An on-board three-pin header is jumpered accordingly
to select the signal, whichever suits the device being triggered.


== Physical

=== Printed Circuit Board

Trace widths must be sufficient minimize circuit impedance, and to
limit temperature rise.  Assume a maximum ambient temperature
(enclosure interior) of 60°C.  Maximum trace temperature rise should
be no more than 20°C.

=== External Connectors

IDEA: Powerpole connectors are mounted to the enclosure with
http://www.portableuniversalpower.com/anderson-autogrip/[Anderson
AutoGrips].  They're robust and inexpensive.
