= PSAS Launch Tower Computer III Design Specification

FIXME: Feel free to make any additions or corrections.  When adding
new content, please reference specific requirements in the Functional
Specification, if appropriate.


== Abstract

The existing launch tower computer (LTC), the second major design
since the group's founding, is due for an overhaul.  It's only been
two years since LTC II was put into service, but there have been rapid
advances in available off-the-shelf technology, and our understanding
of what we need (and don't want) in an LTC has continued to evolve.

This document describes how the new LTC design will be implemented (as
opposed to what it should do for us, which is the domain of the
Functional Specification).


== Design Overview

* BeagleBone Black SBC
* Peripherals (sensors, relays, etc.) contained on a single custom
  PCB.
* BBB flipped upside down and mated to peripheral board via pin
  headers.  A kilt, rather than a cape!
* Replace lead-acid (car) batteries with high-capacity LiPo cells.
* Use a battery module in common with the rocket.
* Improved enclosure-to-tower mounting apparatus.
* Detectable rocket umbilical connection state.
* Improved external connectors (more robust).
* Improved labeling of various components, connectors, switches, etc.
* Thermal analysis!
* Smaller, metal enclosure; https://en.wikipedia.org/wiki/DIN_rail[DIN rail] mounting (or something
  similar).

=== External Interface

* Rocket umbilical
* Away box
* WiFi coax
* Power + Ethernet spare (future capacity)
* Debug Ethernet
* Camera triggers


== Design Details

=== Power Distribution Subsystem

* Solar power in
* Battery charger
* Main battery
* Ignition battery

=== Ignition Subsystem

TODO: words


== External References

http://kilobaser.com/blog/2014-07-15-beaglebone-black-gpios["BeagleBone
Black GPIOs"], KiloBaser.



== Unanswered Questions
* Combine LTC2's power and ignition boards into one single board for
  LTC3, or keep functional separation and create several small
  "capes" that stack on top of the BBB?
