= Portland State Aerospace Society Launch Tower Computer III Design Specification
PSAS Avionics Team <psas-avionics@lists.psas.pdx.edu>
v0.1, 14 April 2015: DRAFT

:imagesdir: ./images


NB: This document is most totally a work in progress.  In fact, you
shouldn't even read the following words unless you're planning on
editing them.  Move along, people...



== Summary

This document is the source of authority for all questions related to
the design and implementation of the LTC III.  If the design of the
LTC doesn't conform to this document, then either the design is
incorrect, or the document needs to be updated!



== Computer

The heart of the Launch Tower Computer III is a BeagleBone Black (BBB)
single-board computer.

The BBB interfaces with the main board via a pair of 46-pin headers.
The main board appears to the BBB as a standard
http://beagleboard.org/cape["cape"].  The main board is on the bottom,
with the BBB mounted on top, upside-down.

=== Cape EEPROM Contents
TODO


== Sensors

LTC3 contains sensors to monitor the voltage on each power rail (12
VDC,
5 VDC, 28.8 VDC

=== Voltage

.Sensors Considered
[cols="1,1,1,3a,3a,1", options="header"]
|===
|Mfr/Vendor
|Model/Part #
|Type
|Features
|Pros & Cons
|Price

|Linear Technologies
|http://cds.linear.com/docs/en/datasheet/2991fd.pdf[LTC2991] Octal I2C Voltage, Current, and Temperature Monitor
|voltage, current and temperature
|* I2C interface
 * up to eight inputs per IC
|* CON: expensive
 * CON: requires complex software to interface
|$11.06, mil-spec, https://www.digikey.com/product-detail/en/LTC2991IMS%23PBF/LTC2991IMS%23PBF-ND/2734961[Digi-Key]

|===

=== Current

.Sensors Considered
[cols="1,1,1,3a,3a,1", options="header"]
|===
|Mfr/Vendor
|Model/Part #
|Type
|Features
|Pros & Cons
|Price

|Texas Instruments
|http://www.ti.com/lit/ds/symlink/ina139.pdf[INA139] High-Side Measurement Current Shunt Monitor
|current
|* analog output
 * one input per IC
|* PRO: inexpensive
 * CON: requires ADC
|$2.15, https://www.digikey.com/product-detail/en/INA139NA%2F250/INA139NA%2F250CT-ND/379721[Digi-Key]

|===

=== Temperature

.Sensors Considered
[cols="1,1,1,3a,3a,1", options="header"]
|===
|Mfr/Vendor
|Model/Part #
|Type
|Features
|Pros & Cons
|Price

|Microchip
|http://www.microchip.com/wwwproducts/Devices.aspx?dDocName=en010749[TC74] Tiny Serial Digital Thermal Sensor
|temperature
|* I2C interface
 * ±3 °C Accuracy from 0 °C to +125 °C
 * Supply Voltage of 2.7 V to 5.5 V
|* PRO: inexpensive
|$1.04, https://www.digikey.com/product-detail/en/TC74A5-5.0VCTTR/TC74A5-5.0VCTCT-ND/459179[Digi-Key]

|Microchip
|http://www.microchip.com/wwwproducts/Devices.aspx?dDocName=en556182[MCP9808] Digital Temperature Sensor
|temperature
|* I2C interface
 * ±0.5 °C (maximum) from -20 °C to +100 °C
 * Supply Voltage of 2.7 V to 5.5 V
 * User-selectable measurement resolution
 * User-selectable temperature limits (via "alert" pin)
|* PRO: inexpensive
|$1.36, https://www.digikey.com/product-detail/en/MCP9808-E%2FMS/MCP9808-E%2FMS-ND/2802083[Digi-Key]

|Texas Instruments
|http://www.ti.com/lit/ds/symlink/tmp102.pdf[TMP102] Low-Power Digital Temperature Sensor w/ Two-Wire Serial Interface
|temperature
|* I2C interface
 * ±0.5 °C without need for calibration
 * Supply Voltage of 1.4 V to 3.6 V
|* PRO: inexpensive
|$2.53, https://www.digikey.com/product-detail/en/TMP102AIDRLT/296-22055-1-ND/1649890[Digi-Key]

|===



== Power

=== Battery

The heart of the LTC3 power circuitry is a 28.8 V, 8s1p LiPo battery
pack.  The 28.8 V nominal voltage enables the use of buck converters
on 5V and 19V power rails.  (Configurable buck converters are cheap
and plentiful, and have higher efficiencies than the boost
converters.)  The 8s1p configuration enables us to charge-balance
individual cells.

The downside of this approach is the need for a custom charging
circuit, as most off-the-shelf chargers are designed for 12V nominal
MPPT and 4s cell configurations.

TODO
* Based on assumptions: 90% efficiency, calc. 96W of power (a
  conservative estimate), 4 hours pure battery, we need a capacity of
  13.2Ah at 28.8V nominal.
* An 8s2p final configuration of 6.7 Ah cells would get
  us into our 4 hours.


=== Battery Charge Controller

LTC3 uses the Linear Technologies LT8490, a switching buck/boost
regulator that integrates a charger and solar MPPT.  It is robust and
inexpensive.  Implementation of circuits based on the LT8490 are
somewhat complicated, but are a big win in terms of cost and system
flexibility.  The LT8490 can be powered with a wide range of input
voltages.  A single connctor can be used for either the solar panels
or 12V bench power supplies.


=== Battery Protection

LiPo cell protection is provided by a Texas Instruments bq77PL900.
The bq77PL900 is a cell protector and charge balancer that is
inexpensive and relatively simple to use.


=== 5 VDC and 12 VDC Power Rails

DC power rails are supplied by separate Texas Instruments PTN78020
switching regulator ICs.  The PTN78020 is a wide-input, wide-output,
adjustable 6 A regulator.  A PTN78020W is used for the 5 VDC rail; a
PTN78020H is used for the 19 VDC rail.



== Ignition Subsystem
* The ignition signal is controlled by two relays in series
** One on the ignition board controlled by RocketReady (from the FC)
** One on the relay board controlled by the LTC



== Networking

* Internal Ethernet switch.


== External Device Support

LTC3 provides power and trigger support for four external devices
(e.g., cameras).

=== Power
Power is supplied through two-terminal Anderson Powerpole connectors,
available from the exterior of the LTC enclosure.  Current to each
connector is limited by a 2 A PPTC (PolyFuse).

Each power connector is controlled independently by the computer.
Photorelays, driven via GPIO through a MOSFET, are used to switch the
12 VDC rail to "Eurostyle" connectors mounted to the mainboard.
Common, 16-gauge stranded copper wire carries current from the
on-board connectors to the exterior-facing Powerpoles.

=== Triggers
Triggering is supplied through two-terminal TODO-CONNECTOR_TYPE
connectors, available from the exterior of the LTC enclosure.  Current
to each connector is limited by a 500mA A PPTC (PolyFuse).

Each trigger connector is controlled independently by the computer.
Photorelays, driven via GPIO through a MOSFET, are used to switch
either ground, or the 5 VDC rail, to "Eurostyle" connectors mounted to
the mainboard.  An on-board three-pin header is jumpered accordingly
to select the signal, whichever suits the device being triggered.


== Physical

=== Printed Circuit Board

Trace widths must be sufficient minimize circuit impedance, and to
limit temperature rise.  Assume a maximum ambient temperature
(enclosure interior) of 60°C.  Maximum trace temperature rise should
be no more than 20°C.

=== External Connectors

IDEA: Powerpole connectors are mounted to the enclosure with
http://www.portableuniversalpower.com/anderson-autogrip/[Anderson
AutoGrips].  They're robust and inexpensive.
